force-app/main/default/objects/Contract_Data__c/Contract_Data__c.object-meta.xml
<CustomObject>
    <label>Contract Data</label>
    <nameField>
        <displayFormat>Contract-{000}</displayFormat>
        <label>Contract Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/components/JumpCloudAssignment/force-app/main/default/objects/Contract_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contract Data</relationshipLabel>
    <relationshipName>Contract_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

src/components/JumpCloudAssignment/force-app/main/default/objects/External_Data__c/External_Data__c.object-meta.xml
<CustomObject>
    <label>External Data</label>
    <nameField>
        <displayFormat>ED-{000}</displayFormat>
        <label>External Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/components/JumpCloudAssignment/force-app/main/default/objects/External_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>External Data</relationshipLabel>
    <relationshipName>External_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ExternalContractControllerTest.cls
@istest
private class ExternalContractControllerTest {
    @istest
    static void testBehavior() {

        account a = new account();
        a.Name = 'Banana Peels Incorporated';
        insert a;

        External_Data__c e = new External_Data__c();
        e.Account__c = a.Id;
        insert e;

        Contract_Data__c c = new Contract_Data__c();
        c.Account__c = a.Id;
        insert c;
        
        Test.startTest();
        System.assertNotEquals(null, ExternalContractController.getExternalList(a.Id));
        System.assertNotEquals(null, ExternalContractController.getContractList(a.Id));
        Test.stopTest();
        

    }
}